#!/usr/bin/env python3
"""Regenerates the frozen seed fixtures from data/seed/ (CUTOVER_PLAN.md §4.2 item 0.1).

Repairs applied to the legacy seed (it does not load against schema/ as shipped):
  * LOCATIONS.PHONE              -> PHONE_NUMBER
  * JOB_GRADES.GRADE_LEVEL       -> GRADE_CODE ('G' || grade)   (GRADE_CODE is NOT NULL)
  * SYSTEM_PARAMETERS.DESCRIPTION -> PARAM_DESCRIPTION

tools/fixtures/oracle/  = repaired Oracle seed (input for tests/utplsql and the golden baseline)
tools/fixtures/pg/      = same rows translated to PostgreSQL (loaded by the Level-1 tests)

The PostgreSQL files end with a sequence sync block: the seed inserts explicit primary keys, so
every sequence backing an inserted table is advanced past max(pk) (only when the seed reached the
sequence's current position, so `seq_employee start with 10000` is left alone). Without it the
first service insert (`nextval('seq_salary')`) collides with the seed rows.

tools/fixtures/pg/04_user_accounts.sql is hand-maintained (PostgreSQL-only login accounts for the
Phase 0 auth tables) and is left untouched by this script.
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SEED = ROOT / "data" / "seed"
ORACLE_OUT = ROOT / "tools" / "fixtures" / "oracle"
PG_OUT = ROOT / "tools" / "fixtures" / "pg"

HEADER = "-- GENERATED by tools/fixtures/generate_fixtures.py from data/seed/ - do not edit by hand.\n"

# table -> (primary key column, PostgreSQL sequence from V1__hrms_schema.sql)
SEQUENCES = {
    "departments": ("dept_id", "seq_department"),
    "job_grades": ("grade_id", "seq_job_grade"),
    "job_titles": ("job_id", "seq_job_title"),
    "employees": ("emp_id", "seq_employee"),
    "employee_history": ("hist_id", "seq_emp_history"),
    "salary_records": ("salary_id", "seq_salary"),
    "pay_elements": ("element_id", "seq_pay_element"),
    "pay_periods": ("period_id", "seq_pay_period"),
    "payroll_runs": ("run_id", "seq_payroll_run"),
    "payroll_details": ("detail_id", "seq_payroll_detail"),
    "leave_types": ("leave_type_id", "seq_leave_type"),
    "leave_balances": ("balance_id", "seq_leave_balance"),
    "leave_requests": ("request_id", "seq_leave_request"),
    "holidays": ("holiday_id", "seq_holiday"),
    "review_cycles": ("cycle_id", "seq_review_cycle"),
    "performance_reviews": ("review_id", "seq_perf_review"),
    "system_parameters": ("param_id", "seq_system_param"),
}


def repair(sql: str) -> str:
    sql = sql.replace("COUNTRY_CODE, PHONE, ACTIVE_FLAG", "COUNTRY_CODE, PHONE_NUMBER, ACTIVE_FLAG")
    sql = sql.replace("PARAM_VALUE, DESCRIPTION,", "PARAM_VALUE, PARAM_DESCRIPTION,")
    sql = sql.replace("(GRADE_ID, GRADE_NAME, GRADE_LEVEL, MIN_SALARY", "(GRADE_ID, GRADE_CODE, GRADE_NAME, MIN_SALARY")

    def grade_values(m: re.Match[str]) -> str:
        head, gid, name, level = m.group(1), m.group(2), m.group(3), m.group(4)
        return f"{head}VALUES ({gid}, 'G{level}', {name},"

    sql = re.sub(
        r"(INSERT INTO JOB_GRADES \([^)]*\)\s*)VALUES \((\d+), ('[^']*'), (\d+),",
        grade_values,
        sql,
    )
    return sql


def to_postgres(sql: str) -> str:
    out = []
    for line in sql.splitlines():
        if line.startswith("SET DEFINE OFF") or line.startswith("COMMIT"):
            continue
        line = re.sub(r"TO_DATE\('(\d{4}-\d{2}-\d{2})', 'YYYY-MM-DD'\)", r"DATE '\1'", line)
        line = line.replace("SYSDATE", "CURRENT_TIMESTAMP")
        line = re.sub(r"^INSERT INTO ([A-Z_]+) \(([A-Z0-9_, ]+)\)", lambda m: f"insert into {m.group(1).lower()} ({m.group(2).lower()})", line)
        line = re.sub(r"^INSERT INTO ([A-Z_]+) \(([A-Z0-9_, ]+)\) VALUES", lambda m: f"insert into {m.group(1).lower()} ({m.group(2).lower()}) values", line)
        line = re.sub(r"^VALUES ", "values ", line)
        out.append(line)
    body = "\n".join(out).rstrip() + "\n"
    return body + sequence_sync(body)


def sequence_sync(pg_sql: str) -> str:
    tables = sorted(set(re.findall(r"^insert into ([a-z_]+) \(", pg_sql, flags=re.M)))
    stmts = []
    for table in tables:
        if table not in SEQUENCES:
            continue
        pk, seq = SEQUENCES[table]
        stmts.append(
            f"select setval('{seq}', max({pk})) from {table}\n"
            f"  having max({pk}) >= (select last_value from {seq});"
        )
    if not stmts:
        return ""
    return "\n-- Advance the sequences past the explicit primary keys inserted above.\n" + "\n".join(stmts) + "\n"


def main() -> None:
    ORACLE_OUT.mkdir(parents=True, exist_ok=True)
    PG_OUT.mkdir(parents=True, exist_ok=True)
    for src in sorted(SEED.glob("*.sql")):
        repaired = repair(src.read_text())
        (ORACLE_OUT / src.name).write_text(HEADER + repaired)
        (PG_OUT / src.name).write_text(HEADER + to_postgres(repaired))
        print(f"wrote {src.name}")


if __name__ == "__main__":
    main()
