#!/usr/bin/env python3
"""Regenerates the frozen seed fixtures from data/seed/ (CUTOVER_PLAN.md §4.2 item 0.1).

Repairs applied to the legacy seed (it does not load against schema/ as shipped):
  * LOCATIONS.PHONE              -> PHONE_NUMBER
  * JOB_GRADES.GRADE_LEVEL       -> GRADE_CODE ('G' || grade)   (GRADE_CODE is NOT NULL)
  * SYSTEM_PARAMETERS.DESCRIPTION -> PARAM_DESCRIPTION

tools/fixtures/oracle/  = repaired Oracle seed (input for tests/utplsql and the golden baseline)
tools/fixtures/pg/      = same rows translated to PostgreSQL (loaded by the Level-1 tests)

tools/fixtures/pg/04_user_accounts.sql is hand-maintained (PostgreSQL-only login accounts for the
Phase 0 auth tables) and is left untouched by this script.
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SEED = ROOT / "data" / "seed"
ORACLE_OUT = ROOT / "tools" / "fixtures" / "oracle"
PG_OUT = ROOT / "tools" / "fixtures" / "pg"

HEADER = "-- GENERATED by tools/fixtures/generate_fixtures.py from data/seed/ - do not edit by hand.\n"


def repair(sql: str) -> str:
    sql = sql.replace("COUNTRY_CODE, PHONE, ACTIVE_FLAG", "COUNTRY_CODE, PHONE_NUMBER, ACTIVE_FLAG")
    sql = sql.replace("PARAM_VALUE, DESCRIPTION,", "PARAM_VALUE, PARAM_DESCRIPTION,")
    sql = sql.replace("(GRADE_ID, GRADE_NAME, GRADE_LEVEL, MIN_SALARY", "(GRADE_ID, GRADE_CODE, GRADE_NAME, MIN_SALARY")

    def grade_values(m: re.Match[str]) -> str:
        head, gid, name, level = m.group(1), m.group(2), m.group(3), m.group(4)
        return f"{head}VALUES ({gid}, 'G{level}', {name},"

    sql = re.sub(
        r"(INSERT INTO JOB_GRADES \([^)]*\)\s*)VALUES \((\d+), ('[^']*'), (\d+),",
        grade_values,
        sql,
    )
    return sql


def to_postgres(sql: str) -> str:
    out = []
    for line in sql.splitlines():
        if line.startswith("SET DEFINE OFF") or line.startswith("COMMIT"):
            continue
        line = re.sub(r"TO_DATE\('(\d{4}-\d{2}-\d{2})', 'YYYY-MM-DD'\)", r"DATE '\1'", line)
        line = line.replace("SYSDATE", "CURRENT_TIMESTAMP")
        line = re.sub(r"^INSERT INTO ([A-Z_]+) \(([A-Z0-9_, ]+)\)", lambda m: f"insert into {m.group(1).lower()} ({m.group(2).lower()})", line)
        line = re.sub(r"^INSERT INTO ([A-Z_]+) \(([A-Z0-9_, ]+)\) VALUES", lambda m: f"insert into {m.group(1).lower()} ({m.group(2).lower()}) values", line)
        line = re.sub(r"^VALUES ", "values ", line)
        out.append(line)
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    ORACLE_OUT.mkdir(parents=True, exist_ok=True)
    PG_OUT.mkdir(parents=True, exist_ok=True)
    for src in sorted(SEED.glob("*.sql")):
        repaired = repair(src.read_text())
        (ORACLE_OUT / src.name).write_text(HEADER + repaired)
        (PG_OUT / src.name).write_text(HEADER + to_postgres(repaired))
        print(f"wrote {src.name}")


if __name__ == "__main__":
    main()
