-- GENERATED by tools/fixtures/generate_fixtures.py from data/seed/ - do not edit by hand.
-- ============================================================================
-- HRMS Reference Data - Seed Script
-- Run order: 01 (before employee data)
-- ============================================================================


-- -----------------------------------------------------------------------
-- LOCATIONS
-- -----------------------------------------------------------------------
insert into locations (location_code, location_name, address_line1, city, state_province, postal_code, country_code, phone_number, active_flag, created_by, created_date)
values ('HQ', 'Corporate Headquarters', '100 Main Street', 'New York', 'NY', '10001', 'US', '212-555-1000', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into locations (location_code, location_name, address_line1, city, state_province, postal_code, country_code, phone_number, active_flag, created_by, created_date)
values ('CHI', 'Chicago Regional Office', '200 Michigan Avenue', 'Chicago', 'IL', '60601', 'US', '312-555-2000', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into locations (location_code, location_name, address_line1, city, state_province, postal_code, country_code, phone_number, active_flag, created_by, created_date)
values ('SF', 'San Francisco Branch', '50 California Street', 'San Francisco', 'CA', '94111', 'US', '415-555-3000', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- JOB GRADES
-- -----------------------------------------------------------------------
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (1, 'G1', 'Entry Level', 35000, 55000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (2, 'G2', 'Junior', 45000, 70000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (3, 'G3', 'Mid-Level', 60000, 90000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (4, 'G4', 'Senior', 80000, 120000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (5, 'G5', 'Lead', 95000, 145000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (6, 'G6', 'Manager', 110000, 170000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (7, 'G7', 'Senior Manager', 130000, 200000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (8, 'G8', 'Director', 160000, 250000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (9, 'G9', 'VP', 200000, 350000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_grades (grade_id, grade_code, grade_name, min_salary, max_salary, active_flag, created_by, created_date)
values (10, 'G10', 'C-Suite', 300000, 600000, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- DEPARTMENTS
-- -----------------------------------------------------------------------
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (1, 'EXEC', 'Executive Office', 'CC-1000', NULL, NULL, 'HQ', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (10, 'HR', 'Human Resources', 'CC-1100', 1, NULL, 'HQ', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (20, 'FIN', 'Finance & Accounting', 'CC-1200', 1, NULL, 'HQ', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (30, 'IT', 'Information Technology', 'CC-1300', 1, NULL, 'CHI', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (31, 'ITDEV', 'IT - Development', 'CC-1310', 30, NULL, 'CHI', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (32, 'ITOPS', 'IT - Operations', 'CC-1320', 30, NULL, 'CHI', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (40, 'SALES', 'Sales', 'CC-1400', 1, NULL, 'SF', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (50, 'MKT', 'Marketing', 'CC-1500', 1, NULL, 'SF', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (60, 'OPS', 'Operations', 'CC-1600', 1, NULL, 'CHI', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into departments (dept_id, dept_code, dept_name, cost_center, parent_dept_id, manager_emp_id, location_code, active_flag, created_by, created_date)
values (70, 'LEGAL', 'Legal & Compliance', 'CC-1700', 1, NULL, 'HQ', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- JOB TITLES
-- -----------------------------------------------------------------------
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (1, 'CEO', 'Chief Executive Officer', 10, '1.1', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (2, 'CFO', 'Chief Financial Officer', 10, '1.1', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (3, 'CIO', 'Chief Information Officer', 10, '1.1', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (10, 'VP-HR', 'VP of Human Resources', 9, '1.1', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (11, 'VP-FIN', 'VP of Finance', 9, '1.1', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (12, 'VP-SALES', 'VP of Sales', 9, '1.1', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (20, 'DIR-IT', 'Director of IT', 8, '1.2', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (21, 'DIR-HR', 'Director of HR', 8, '1.2', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (30, 'MGR-DEV', 'Development Manager', 6, '1.2', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (31, 'MGR-OPS', 'Operations Manager', 6, '1.2', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (32, 'MGR-PAY', 'Payroll Manager', 6, '1.2', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (33, 'MGR-SALES', 'Sales Manager', 6, '1.2', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (40, 'SR-DEV', 'Senior Developer', 4, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (41, 'SR-DBA', 'Senior DBA', 4, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (42, 'SR-ACCT', 'Senior Accountant', 4, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (43, 'SR-SALES', 'Senior Sales Rep', 4, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (50, 'DEV', 'Software Developer', 3, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (51, 'QA', 'QA Analyst', 3, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (52, 'ACCT', 'Accountant', 3, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (53, 'HR-SPEC', 'HR Specialist', 3, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (54, 'SALES-REP', 'Sales Representative', 3, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (60, 'JR-DEV', 'Junior Developer', 2, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (61, 'HR-ASST', 'HR Assistant', 2, '5.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (62, 'ACCT-CLK', 'Accounting Clerk', 2, '5.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (70, 'INTERN', 'Intern', 1, '2.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into job_titles (job_id, job_code, job_title, grade_id, eeo_category, active_flag, created_by, created_date) VALUES (71, 'RECEPT', 'Receptionist', 1, '5.0', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- LEAVE TYPES
-- -----------------------------------------------------------------------
insert into leave_types (leave_type_id, leave_type_code, leave_type_name, accrual_flag, accrual_rate, accrual_frequency, max_balance, carryover_max, carryover_expiry, requires_approval, min_tenure_days, active_flag, created_by, created_date)
values (1, 'PTO', 'Paid Time Off', 'Y', 1.25, 'MONTHLY', 20, 5, 3, 'Y', 0, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into leave_types (leave_type_id, leave_type_code, leave_type_name, accrual_flag, accrual_rate, accrual_frequency, max_balance, carryover_max, carryover_expiry, requires_approval, min_tenure_days, active_flag, created_by, created_date)
values (2, 'SICK', 'Sick Leave', 'Y', 0.833, 'MONTHLY', 10, 10, NULL, 'Y', 0, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into leave_types (leave_type_id, leave_type_code, leave_type_name, accrual_flag, accrual_rate, accrual_frequency, max_balance, carryover_max, carryover_expiry, requires_approval, min_tenure_days, active_flag, created_by, created_date)
values (3, 'COMP', 'Compensatory Time', 'N', NULL, NULL, NULL, 0, NULL, 'Y', 90, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into leave_types (leave_type_id, leave_type_code, leave_type_name, accrual_flag, accrual_rate, accrual_frequency, max_balance, carryover_max, carryover_expiry, requires_approval, min_tenure_days, active_flag, created_by, created_date)
values (4, 'FMLA', 'Family Medical Leave', 'N', NULL, NULL, NULL, 0, NULL, 'Y', 365, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into leave_types (leave_type_id, leave_type_code, leave_type_name, accrual_flag, accrual_rate, accrual_frequency, max_balance, carryover_max, carryover_expiry, requires_approval, min_tenure_days, active_flag, created_by, created_date)
values (5, 'JURY', 'Jury Duty', 'N', NULL, NULL, NULL, 0, NULL, 'N', 0, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into leave_types (leave_type_id, leave_type_code, leave_type_name, accrual_flag, accrual_rate, accrual_frequency, max_balance, carryover_max, carryover_expiry, requires_approval, min_tenure_days, active_flag, created_by, created_date)
values (6, 'BEREAVE', 'Bereavement', 'N', NULL, NULL, NULL, 0, NULL, 'N', 0, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- PAY ELEMENTS
-- -----------------------------------------------------------------------
insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (1, 'BASE_PAY', 'Base Salary', 'EARNING', 'FLAT', NULL, NULL, '5100-100', 1, 'N', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (100, 'FED_TAX', 'Federal Income Tax', 'TAX', 'FORMULA', NULL, NULL, '2100-100', 10, 'N', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (101, 'STATE_TAX', 'State Income Tax', 'TAX', 'FORMULA', NULL, NULL, '2100-200', 11, 'N', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (102, 'FICA', 'Social Security (FICA)', 'TAX', 'FORMULA', NULL, NULL, '2100-300', 12, 'N', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (103, 'MEDICARE', 'Medicare', 'TAX', 'FORMULA', NULL, NULL, '2100-400', 13, 'N', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (200, '401K_EE', '401(k) Employee Contribution', 'DEDUCTION', 'PERCENTAGE', NULL, 6, '2200-100', 20, 'Y', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (201, 'MED_EE', 'Medical Insurance (Employee)', 'BENEFIT', 'FLAT', 250, NULL, '2200-200', 21, 'Y', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (202, 'DENTAL_EE', 'Dental Insurance (Employee)', 'BENEFIT', 'FLAT', 45, NULL, '2200-300', 22, 'Y', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (203, 'VISION_EE', 'Vision Insurance (Employee)', 'BENEFIT', 'FLAT', 15, NULL, '2200-400', 23, 'Y', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (204, 'LIFE_INS', 'Life Insurance', 'BENEFIT', 'FLAT', 25, NULL, '2200-500', 24, 'N', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type, default_amount, default_percentage, gl_account_code, priority_order, pretax_flag, active_flag, created_by, created_date)
values (205, 'HSA', 'Health Savings Account', 'DEDUCTION', 'FLAT', 150, NULL, '2200-600', 25, 'Y', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- HOLIDAYS (2024-2025)
-- -----------------------------------------------------------------------
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (1, 'New Year''s Day', DATE '2024-01-01', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (2, 'Martin Luther King Jr. Day', DATE '2024-01-15', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (3, 'Presidents'' Day', DATE '2024-02-19', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (4, 'Memorial Day', DATE '2024-05-27', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (5, 'Independence Day', DATE '2024-07-04', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (6, 'Labor Day', DATE '2024-09-02', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (7, 'Thanksgiving', DATE '2024-11-28', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (8, 'Day After Thanksgiving', DATE '2024-11-29', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (9, 'Christmas Eve', DATE '2024-12-24', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into holidays (holiday_id, holiday_name, holiday_date, location_code, active_flag, created_by, created_date)
values (10, 'Christmas Day', DATE '2024-12-25', NULL, 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- SYSTEM PARAMETERS
-- -----------------------------------------------------------------------
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (1, 'SYSTEM', 'APP_VERSION', '4.2.0', 'Application version', 'N', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (2, 'SYSTEM', 'COMPANY_NAME', 'Acme Corporation', 'Company name', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (3, 'PAYROLL', 'DEFAULT_PAY_FREQUENCY', 'MONTHLY', 'Default payroll frequency', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (4, 'PAYROLL', 'FISCAL_YEAR_START', '10', 'Fiscal year start month', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (5, 'SECURITY', 'SESSION_TIMEOUT_MIN', '30', 'Session timeout in minutes', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (6, 'SECURITY', 'PASSWORD_MIN_LENGTH', '8', 'Minimum password length', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (7, 'NOTIFICATION', 'SMTP_HOST', 'smtp.internal.company.com', 'SMTP server hostname', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (8, 'NOTIFICATION', 'FROM_ADDRESS', 'hrms-noreply@company.com', 'Default from address', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (9, 'INTEGRATION', 'GL_FEED_STATUS', 'ACTIVE', 'GL integration status', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, editable_flag, created_by, created_date)
values (10, 'INTEGRATION', 'BENEFITS_FEED_STATUS', 'ACTIVE', 'Benefits feed status', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- Advance the sequences past the explicit primary keys inserted above.
select setval('seq_department', max(dept_id)) from departments
  having max(dept_id) >= (select last_value from seq_department);
select setval('seq_holiday', max(holiday_id)) from holidays
  having max(holiday_id) >= (select last_value from seq_holiday);
select setval('seq_job_grade', max(grade_id)) from job_grades
  having max(grade_id) >= (select last_value from seq_job_grade);
select setval('seq_job_title', max(job_id)) from job_titles
  having max(job_id) >= (select last_value from seq_job_title);
select setval('seq_leave_type', max(leave_type_id)) from leave_types
  having max(leave_type_id) >= (select last_value from seq_leave_type);
select setval('seq_pay_element', max(element_id)) from pay_elements
  having max(element_id) >= (select last_value from seq_pay_element);
select setval('seq_system_param', max(param_id)) from system_parameters
  having max(param_id) >= (select last_value from seq_system_param);
