-- GENERATED by tools/fixtures/generate_fixtures.py from data/seed/ - do not edit by hand.
-- ============================================================================
-- HRMS Employee Sample Data - Seed Script
-- Run order: 02 (after reference data)
-- Includes 25 employees across departments with salary records
-- ============================================================================


-- -----------------------------------------------------------------------
-- EMPLOYEES
-- -----------------------------------------------------------------------

-- Executive
insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (1, 'EMP-000001', 'JAMES', 'RICHARDSON', 'james.richardson@company.com', '212-555-1001', DATE '2010-03-15', 1, 1, NULL, 'HQ', 'FULL_TIME', 'ACTIVE', 'M', DATE '1968-07-22', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (2, 'EMP-000002', 'SARAH', 'CHEN', 'sarah.chen@company.com', '212-555-1002', DATE '2012-06-01', 20, 2, 1, 'HQ', 'FULL_TIME', 'ACTIVE', 'F', DATE '1975-11-03', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (3, 'EMP-000003', 'MICHAEL', 'OCONNOR', 'michael.oconnor@company.com', '312-555-2001', DATE '2011-09-12', 30, 3, 1, 'CHI', 'FULL_TIME', 'ACTIVE', 'M', DATE '1972-03-18', 'DIVORCED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- HR Department
insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (10, 'EMP-000010', 'PATRICIA', 'WILLIAMS', 'patricia.williams@company.com', '212-555-1101', DATE '2013-02-18', 10, 10, 1, 'HQ', 'FULL_TIME', 'ACTIVE', 'F', DATE '1978-09-14', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (11, 'EMP-000011', 'DAVID', 'MARTINEZ', 'david.martinez@company.com', '212-555-1102', DATE '2016-08-22', 10, 53, 10, 'HQ', 'FULL_TIME', 'ACTIVE', 'M', DATE '1985-04-30', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (12, 'EMP-000012', 'EMILY', 'JOHNSON', 'emily.johnson@company.com', '212-555-1103', DATE '2019-01-07', 10, 61, 10, 'HQ', 'FULL_TIME', 'ACTIVE', 'F', DATE '1994-12-08', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- Finance Department
insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (20, 'EMP-000020', 'ROBERT', 'KUMAR', 'robert.kumar@company.com', '212-555-1201', DATE '2014-05-12', 20, 11, 2, 'HQ', 'FULL_TIME', 'ACTIVE', 'M', DATE '1980-01-25', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (21, 'EMP-000021', 'JENNIFER', 'PARK', 'jennifer.park@company.com', '212-555-1202', DATE '2017-03-20', 20, 32, 20, 'HQ', 'FULL_TIME', 'ACTIVE', 'F', DATE '1983-06-17', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (22, 'EMP-000022', 'THOMAS', 'BAKER', 'thomas.baker@company.com', '212-555-1203', DATE '2018-09-10', 20, 42, 21, 'HQ', 'FULL_TIME', 'ACTIVE', 'M', DATE '1987-02-14', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (23, 'EMP-000023', 'LISA', 'WONG', 'lisa.wong@company.com', '212-555-1204', DATE '2020-11-02', 20, 52, 21, 'HQ', 'FULL_TIME', 'ACTIVE', 'F', DATE '1992-08-21', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (24, 'EMP-000024', 'ANDREW', 'PATEL', 'andrew.patel@company.com', '212-555-1205', DATE '2022-06-15', 20, 62, 21, 'HQ', 'FULL_TIME', 'ACTIVE', 'M', DATE '1997-10-30', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- IT Department
insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (30, 'EMP-000030', 'RACHEL', 'THOMPSON', 'rachel.thompson@company.com', '312-555-2101', DATE '2015-01-05', 30, 20, 3, 'CHI', 'FULL_TIME', 'ACTIVE', 'F', DATE '1979-05-12', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (31, 'EMP-000031', 'KEVIN', 'GARCIA', 'kevin.garcia@company.com', '312-555-2102', DATE '2016-04-18', 31, 30, 30, 'CHI', 'FULL_TIME', 'ACTIVE', 'M', DATE '1984-11-07', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (32, 'EMP-000032', 'MARIA', 'RODRIGUEZ', 'maria.rodriguez@company.com', '312-555-2103', DATE '2017-07-24', 31, 40, 31, 'CHI', 'FULL_TIME', 'ACTIVE', 'F', DATE '1986-03-29', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (33, 'EMP-000033', 'DANIEL', 'LEE', 'daniel.lee@company.com', '312-555-2104', DATE '2018-02-12', 31, 41, 31, 'CHI', 'FULL_TIME', 'ACTIVE', 'M', DATE '1982-09-05', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (34, 'EMP-000034', 'JESSICA', 'NGUYEN', 'jessica.nguyen@company.com', '312-555-2105', DATE '2019-05-06', 31, 50, 31, 'CHI', 'FULL_TIME', 'ACTIVE', 'F', DATE '1991-07-15', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (35, 'EMP-000035', 'CHRIS', 'ANDERSON', 'chris.anderson@company.com', '312-555-2106', DATE '2020-08-17', 31, 50, 31, 'CHI', 'FULL_TIME', 'ACTIVE', 'M', DATE '1993-01-22', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (36, 'EMP-000036', 'PRIYA', 'SHARMA', 'priya.sharma@company.com', '312-555-2107', DATE '2021-03-22', 31, 51, 31, 'CHI', 'FULL_TIME', 'ACTIVE', 'F', DATE '1995-06-10', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (37, 'EMP-000037', 'ALEX', 'TAYLOR', 'alex.taylor@company.com', '312-555-2108', DATE '2022-01-10', 31, 60, 31, 'CHI', 'FULL_TIME', 'ACTIVE', 'M', DATE '1998-04-18', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- Sales Department
insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (40, 'EMP-000040', 'MARK', 'DAVIS', 'mark.davis@company.com', '415-555-3101', DATE '2014-11-03', 40, 12, 1, 'SF', 'FULL_TIME', 'ACTIVE', 'M', DATE '1977-08-09', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (41, 'EMP-000041', 'ASHLEY', 'BROWN', 'ashley.brown@company.com', '415-555-3102', DATE '2017-06-19', 40, 33, 40, 'SF', 'FULL_TIME', 'ACTIVE', 'F', DATE '1985-02-28', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (42, 'EMP-000042', 'JASON', 'WILSON', 'jason.wilson@company.com', '415-555-3103', DATE '2019-09-16', 40, 43, 41, 'SF', 'FULL_TIME', 'ACTIVE', 'M', DATE '1989-12-01', 'MARRIED', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (43, 'EMP-000043', 'SAMANTHA', 'MOORE', 'samantha.moore@company.com', '415-555-3104', DATE '2021-02-08', 40, 54, 41, 'SF', 'FULL_TIME', 'ACTIVE', 'F', DATE '1993-10-25', 'SINGLE', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- Terminated employee (for historical queries)
insert into employees (emp_id, emp_number, first_name, last_name, email, phone_work, hire_date, dept_id, job_id, manager_emp_id, location_code, employment_type, employment_status, termination_date, termination_reason, gender, date_of_birth, marital_status, active_flag, created_by, created_date)
values (99, 'EMP-000099', 'BRIAN', 'FOSTER', 'brian.foster@company.com', '312-555-2199', DATE '2018-04-02', 31, 50, 31, 'CHI', 'FULL_TIME', 'TERMINATED', DATE '2023-06-30', 'VOLUNTARY', 'M', DATE '1990-05-14', 'SINGLE', 'N', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- SALARY RECORDS (current active salaries)
-- -----------------------------------------------------------------------
insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (1, 1, DATE '2023-01-01', NULL, 450000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (2, 2, DATE '2023-01-01', NULL, 380000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (3, 3, DATE '2023-01-01', NULL, 370000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (10, 10, DATE '2023-07-01', NULL, 240000, 'USD', 'MONTHLY', 'ANNUAL', 'Promotion', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (11, 11, DATE '2023-01-01', NULL, 78000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (12, 12, DATE '2023-01-01', NULL, 52000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (20, 20, DATE '2023-01-01', NULL, 260000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (21, 21, DATE '2023-01-01', NULL, 135000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (22, 22, DATE '2023-01-01', NULL, 95000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (23, 23, DATE '2023-01-01', NULL, 72000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (24, 24, DATE '2022-06-15', NULL, 48000, 'USD', 'MONTHLY', 'ANNUAL', 'New hire', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (30, 30, DATE '2023-01-01', NULL, 195000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (31, 31, DATE '2023-01-01', NULL, 145000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (32, 32, DATE '2023-01-01', NULL, 115000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (33, 33, DATE '2023-01-01', NULL, 110000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (34, 34, DATE '2023-01-01', NULL, 82000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (35, 35, DATE '2023-01-01', NULL, 78000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (36, 36, DATE '2023-01-01', NULL, 70000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (37, 37, DATE '2022-01-10', NULL, 55000, 'USD', 'MONTHLY', 'ANNUAL', 'New hire', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (40, 40, DATE '2023-01-01', NULL, 280000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (41, 41, DATE '2023-01-01', NULL, 130000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (42, 42, DATE '2023-01-01', NULL, 105000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

insert into salary_records (salary_id, emp_id, effective_date, end_date, base_salary, currency_code, pay_frequency, salary_basis, change_reason, active_flag, created_by, created_date)
values (43, 43, DATE '2023-01-01', NULL, 65000, 'USD', 'MONTHLY', 'ANNUAL', 'Annual review', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- EMPLOYEE TAX INFO (2024 W-4 data read by PKG_PAYROLL.calculate_employee_pay)
-- Employees without a row keep the legacy defaults (SINGLE / 0 allowances / no state).
-- Covers: NY + CA + IL state tax, MARRIED_JOINT / MARRIED_SEPARATE ladders,
-- allowances, additional federal withholding and a zero-rate state (TX).
-- -----------------------------------------------------------------------
insert into employee_tax_info (tax_info_id, emp_id, tax_year, filing_status, federal_allowances, state_allowances, additional_fed_wh, additional_state_wh, exempt_flag, state_code, w4_received_date, active_flag, created_by, created_date)
values (1, 1, 2024, 'MARRIED_JOINT', 2, 2, 250.00, 0, 'N', 'NY', DATE '2024-01-08', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_tax_info (tax_info_id, emp_id, tax_year, filing_status, federal_allowances, state_allowances, additional_fed_wh, additional_state_wh, exempt_flag, state_code, w4_received_date, active_flag, created_by, created_date)
values (2, 20, 2024, 'MARRIED_JOINT', 0, 0, 0, 0, 'N', 'NY', DATE '2024-01-10', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_tax_info (tax_info_id, emp_id, tax_year, filing_status, federal_allowances, state_allowances, additional_fed_wh, additional_state_wh, exempt_flag, state_code, w4_received_date, active_flag, created_by, created_date)
values (3, 30, 2024, 'MARRIED_SEPARATE', 0, 0, 0, 0, 'N', 'TX', DATE '2024-01-15', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_tax_info (tax_info_id, emp_id, tax_year, filing_status, federal_allowances, state_allowances, additional_fed_wh, additional_state_wh, exempt_flag, state_code, w4_received_date, active_flag, created_by, created_date)
values (4, 34, 2024, 'SINGLE', 1, 1, 0, 0, 'N', 'IL', DATE '2024-01-22', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_tax_info (tax_info_id, emp_id, tax_year, filing_status, federal_allowances, state_allowances, additional_fed_wh, additional_state_wh, exempt_flag, state_code, w4_received_date, active_flag, created_by, created_date)
values (5, 40, 2024, 'MARRIED_JOINT', 1, 1, 0, 0, 'N', 'CA', DATE '2024-01-09', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_tax_info (tax_info_id, emp_id, tax_year, filing_status, federal_allowances, state_allowances, additional_fed_wh, additional_state_wh, exempt_flag, state_code, w4_received_date, active_flag, created_by, created_date)
values (6, 41, 2024, 'SINGLE', 0, 0, 50.00, 0, 'N', 'CA', DATE '2024-02-01', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);

-- -----------------------------------------------------------------------
-- EMPLOYEE BANK ACCOUNTS (masked on the pay register: bank name + last 4 of routing / account)
-- account_number_enc is the Java wire format enc:<keyId>:<base64(iv||ct||tag)> produced with the
-- Level-1 test key (hrms.auth.encryption key-id=test-k1, backend/auth/src/test/resources/
-- application-test.yml). Under any other key it is undecryptable and the register prints "****"
-- for ACCOUNT_LAST4, exactly like a legacy ciphertext awaiting CDC re-encryption.
-- -----------------------------------------------------------------------
insert into employee_bank_accounts (bank_acct_id, emp_id, bank_name, routing_number, account_number_enc, account_type, deposit_type, deposit_amount, deposit_percentage, priority_order, prenote_sent, prenote_date, active_flag, created_by, created_date)
values (1, 1, 'First National Bank', '021000021', 'enc:test-k1:213aIihkQv+eNFreEQlsomrVZfZ/wFEtf8F43f43NUyt/mKSA4y4Ww8=', 'CHECKING', 'FULL', NULL, NULL, 1, 'Y', DATE '2010-03-20', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_bank_accounts (bank_acct_id, emp_id, bank_name, routing_number, account_number_enc, account_type, deposit_type, deposit_amount, deposit_percentage, priority_order, prenote_sent, prenote_date, active_flag, created_by, created_date)
values (2, 2, 'Metro Credit Union', '026009593', 'enc:test-k1:pMvqXnv01yYSEkz43HRROLByRHAtV/JdNy6cVxUxYgJaAzAChVWGdEU=', 'CHECKING', 'FULL', NULL, NULL, 1, 'Y', DATE '2012-06-05', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_bank_accounts (bank_acct_id, emp_id, bank_name, routing_number, account_number_enc, account_type, deposit_type, deposit_amount, deposit_percentage, priority_order, prenote_sent, prenote_date, active_flag, created_by, created_date)
values (3, 20, 'Metro Credit Union', '026009593', 'enc:test-k1:cGHdljgVODIcE/hSTBl19Em/F4X+BsIaA8sFxkdKprWK0q7QIF7cGkhTNCU=', 'SAVINGS', 'PARTIAL_AMOUNT', 500.00, NULL, 1, 'Y', DATE '2014-05-15', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_bank_accounts (bank_acct_id, emp_id, bank_name, routing_number, account_number_enc, account_type, deposit_type, deposit_amount, deposit_percentage, priority_order, prenote_sent, prenote_date, active_flag, created_by, created_date)
values (4, 20, 'First National Bank', '021000021', 'enc:test-k1:0KqCCF58CdKg6/UC2XqsdFeMBpM6SkI9GOWXtErKkyakQlQZ1461UHR9naI=', 'CHECKING', 'REMAINDER', NULL, NULL, 2, 'Y', DATE '2014-05-15', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_bank_accounts (bank_acct_id, emp_id, bank_name, routing_number, account_number_enc, account_type, deposit_type, deposit_amount, deposit_percentage, priority_order, prenote_sent, prenote_date, active_flag, created_by, created_date)
values (5, 40, 'Pacific Coast Bank', '121000358', 'enc:test-k1:mevKdWY/ns4v//9B0PXCykXC3rRxAYQb0GS2gAWrE5cNqNKxFYWOfi3ky+w=', 'CHECKING', 'FULL', NULL, NULL, 1, 'Y', DATE '2014-11-08', 'Y', 'SYSTEM', CURRENT_TIMESTAMP);
insert into employee_bank_accounts (bank_acct_id, emp_id, bank_name, routing_number, account_number_enc, account_type, deposit_type, deposit_amount, deposit_percentage, priority_order, prenote_sent, prenote_date, active_flag, created_by, created_date)
values (6, 41, 'Pacific Coast Bank', '121000358', 'enc:test-k1:LhGsdnvSRtjdkgN5O1l8faeIdTIC1euy3cpyYP89E4FVOSsn5JJkQFbbJio=', 'CHECKING', 'FULL', NULL, NULL, 1, 'N', NULL, 'N', 'SYSTEM', CURRENT_TIMESTAMP);

-- Update department managers
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 10 WHERE DEPT_ID = 10;
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 2 WHERE DEPT_ID = 20;
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 3 WHERE DEPT_ID = 30;
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 30 WHERE DEPT_ID = 30;  -- Dir IT manages IT
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 31 WHERE DEPT_ID = 31;
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 40 WHERE DEPT_ID = 40;
UPDATE DEPARTMENTS SET MANAGER_EMP_ID = 1 WHERE DEPT_ID = 1;

-- Advance the sequences past the explicit primary keys inserted above.
select setval('seq_employee', max(emp_id)) from employees
  having max(emp_id) >= (select last_value from seq_employee);
select setval('seq_salary', max(salary_id)) from salary_records
  having max(salary_id) >= (select last_value from seq_salary);
