-- GENERATED by tools/fixtures/generate_fixtures.py from data/seed/ - do not edit by hand.
-- ============================================================================
-- HRMS Transactional Sample Data - Seed Script
-- Run order: 03 (after employee data)
-- Leave balances/requests, one approved payroll run, one in-flight review
-- cycle so that VW_LEAVE_SUMMARY, VW_PAYROLL_LATEST and VW_PENDING_APPROVALS
-- reconcile on real rows (TEST_STRATEGY.md §5 row 0). Every date is fixed
-- (no CURRENT_TIMESTAMP) so the golden baseline is reproducible for --as-of 2024-06-30.
-- ============================================================================


-- -----------------------------------------------------------------------
-- LEAVE_BALANCES (calendar year 2024; one 2023 carry row and one row for a
-- terminated employee are deliberately present and must be filtered out by
-- VW_LEAVE_SUMMARY)
-- -----------------------------------------------------------------------

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9001, 2, 1, 2024, 5, 7.5, 3, 0, 0, 5, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9002, 2, 2, 2024, 0, 5, 1, 0, 0, 0, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9003, 11, 1, 2024, 2, 7.5, 4, 0, 0, 2, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9004, 12, 1, 2024, 0, 7.5, 2, 1, 0, 0, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9005, 12, 2, 2024, 0, 5, 1, 0, 0, 0, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9006, 21, 1, 2024, 4, 7.5, 0, 0, 0, 4, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9007, 22, 1, 2024, 3, 7.5, 2, 0, 5, 3, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9008, 23, 1, 2024, 0, 7.5, 0, 0, 2.5, 0, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9009, 31, 1, 2024, 5, 7.5, 6, 0, 0, 5, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9010, 33, 1, 2024, 0, 7.5, 0, -1, 0, 0, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9011, 42, 1, 2024, 1, 7.5, 1, 0, 3, 1, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9012, 99, 1, 2024, 0, 2.5, 0, 0, 0, 0, 'SYSTEM', DATE '2024-01-01');

insert into leave_balances (balance_id, emp_id, leave_type_id, calendar_year, opening_balance, accrued, used, adjustment, pending, carryover_from_prev, created_by, created_date)
values (9013, 2, 1, 2023, 0, 15, 10, 0, 0, 0, 'SYSTEM', DATE '2023-01-01');

-- -----------------------------------------------------------------------
-- LEAVE_REQUESTS (three PENDING rows feed VW_PENDING_APPROVALS)
-- -----------------------------------------------------------------------

insert into leave_requests (request_id, emp_id, leave_type_id, start_date, end_date, total_days, half_day_flag, status, reason, approver_emp_id, created_by, created_date)
values (1001, 22, 1, DATE '2024-07-08', DATE '2024-07-12', 5, 'N', 'PENDING', 'Summer vacation', 21, 'thomas.baker@company.com', DATE '2024-06-20');

insert into leave_requests (request_id, emp_id, leave_type_id, start_date, end_date, total_days, half_day_flag, status, reason, approver_emp_id, approval_date, created_by, created_date)
values (1002, 12, 2, DATE '2024-06-03', DATE '2024-06-03', 1, 'N', 'APPROVED', 'Doctor appointment', 10, DATE '2024-06-02', 'emily.johnson@company.com', DATE '2024-06-01');

insert into leave_requests (request_id, emp_id, leave_type_id, start_date, end_date, total_days, half_day_flag, half_day_period, status, reason, approver_emp_id, created_by, created_date)
values (1003, 23, 1, DATE '2024-08-01', DATE '2024-08-05', 2.5, 'Y', 'PM', 'PENDING', 'Family event', 21, 'lisa.wong@company.com', DATE '2024-06-25');

insert into leave_requests (request_id, emp_id, leave_type_id, start_date, end_date, total_days, half_day_flag, status, reason, approver_emp_id, approval_date, approval_comments, created_by, created_date)
values (1004, 33, 1, DATE '2024-05-13', DATE '2024-05-14', 2, 'N', 'REJECTED', 'Personal', 31, DATE '2024-05-10', 'Release week - please reschedule', 'daniel.lee@company.com', DATE '2024-05-09');

insert into leave_requests (request_id, emp_id, leave_type_id, start_date, end_date, total_days, half_day_flag, status, reason, approver_emp_id, created_by, created_date)
values (1005, 42, 1, DATE '2024-09-02', DATE '2024-09-04', 3, 'N', 'PENDING', 'Long weekend', 41, 'jason.wilson@company.com', DATE '2024-06-28');

-- -----------------------------------------------------------------------
-- PAY_PERIODS / PAYROLL_RUNS / PAYROLL_DETAILS
-- Run 9001 (MAY-2024) is APPROVED and is the run VW_PAYROLL_LATEST reports;
-- run 9002 (JUN-2024) is only CALCULATED. Taxes/deductions are stored negative.
-- -----------------------------------------------------------------------

insert into pay_periods (period_id, period_name, pay_frequency, period_start_date, period_end_date, pay_date, status, closed_by, closed_date, created_by, created_date)
values (202405, 'MAY-2024', 'MONTHLY', DATE '2024-05-01', DATE '2024-05-31', DATE '2024-05-31', 'CLOSED', 'jennifer.park@company.com', DATE '2024-05-31', 'SYSTEM', DATE '2024-04-25');

insert into pay_periods (period_id, period_name, pay_frequency, period_start_date, period_end_date, pay_date, status, created_by, created_date)
values (202406, 'JUN-2024', 'MONTHLY', DATE '2024-06-01', DATE '2024-06-30', DATE '2024-06-28', 'OPEN', 'SYSTEM', DATE '2024-05-25');

insert into payroll_runs (run_id, period_id, run_type, run_date, status, total_gross, total_deductions, total_net, total_employer_cost, employee_count, error_count, submitted_by, submitted_date, approved_by, approved_date, created_by, created_date)
values (9001, 202405, 'REGULAR', DATE '2024-05-28', 'APPROVED', 47916.67, 19218.95, 28697.72, 51582.60, 4, 1, 'jennifer.park@company.com', DATE '2024-05-29', 'sarah.chen@company.com', DATE '2024-05-30', 'jennifer.park@company.com', DATE '2024-05-28');

insert into payroll_runs (run_id, period_id, run_type, run_date, status, total_gross, total_deductions, total_net, employee_count, error_count, created_by, created_date)
values (9002, 202406, 'REGULAR', DATE '2024-06-26', 'CALCULATED', 20833.33, 0, 20833.33, 1, 0, 'jennifer.park@company.com', DATE '2024-06-26');

-- run 9001 / emp 2
insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10001, 9001, 2, 1, 'EARNING', 20833.33, 104166.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10002, 9001, 2, 100, 'TAX', -4583.33, -22916.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10003, 9001, 2, 101, 'TAX', -1250.00, -6250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10004, 9001, 2, 102, 'TAX', -1291.67, -6458.35, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10005, 9001, 2, 103, 'TAX', -302.08, -1510.40, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10006, 9001, 2, 200, 'DEDUCTION', -1250.00, -6250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10007, 9001, 2, 201, 'BENEFIT', -250.00, -1250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

-- run 9001 / emp 21
insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10011, 9001, 21, 1, 'EARNING', 9166.67, 45833.35, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10012, 9001, 21, 100, 'TAX', -1650.00, -8250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10013, 9001, 21, 101, 'TAX', -458.33, -2291.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10014, 9001, 21, 102, 'TAX', -568.33, -2841.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10015, 9001, 21, 103, 'TAX', -132.92, -664.60, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10016, 9001, 21, 200, 'DEDUCTION', -550.00, -2750.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10017, 9001, 21, 201, 'BENEFIT', -250.00, -1250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10018, 9001, 21, 202, 'BENEFIT', -45.00, -225.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

-- run 9001 / emp 22
insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10021, 9001, 22, 1, 'EARNING', 6250.00, 31250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10022, 9001, 22, 100, 'TAX', -937.50, -4687.50, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10023, 9001, 22, 101, 'TAX', -312.50, -1562.50, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10024, 9001, 22, 102, 'TAX', -387.50, -1937.50, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10025, 9001, 22, 103, 'TAX', -90.63, -453.15, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10026, 9001, 22, 205, 'DEDUCTION', -150.00, -750.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

-- run 9001 / emp 31 (one ERROR row, excluded by the view)
insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10031, 9001, 31, 1, 'EARNING', 11666.67, 58333.35, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10032, 9001, 31, 100, 'TAX', -2333.33, -11666.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10033, 9001, 31, 101, 'TAX', -583.33, -2916.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10034, 9001, 31, 102, 'TAX', -723.33, -3616.65, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10035, 9001, 31, 103, 'TAX', -169.17, -845.85, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10036, 9001, 31, 200, 'DEDUCTION', -700.00, -3500.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (10037, 9001, 31, 201, 'BENEFIT', -250.00, -1250.00, 'CALCULATED', 'SYSTEM', DATE '2024-05-28');

insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, error_message, created_by, created_date)
values (10038, 9001, 31, 205, 'DEDUCTION', 0, -600.00, 'ERROR', 'HSA election missing for 2024', 'SYSTEM', DATE '2024-05-28');

-- run 9002 / emp 2 (run not approved, must not appear in VW_PAYROLL_LATEST)
insert into payroll_details (detail_id, run_id, emp_id, element_id, element_type, amount, ytd_amount, status, created_by, created_date)
values (20001, 9002, 2, 1, 'EARNING', 20833.33, 124999.98, 'CALCULATED', 'SYSTEM', DATE '2024-06-26');

-- -----------------------------------------------------------------------
-- REVIEW_CYCLES / PERFORMANCE_REVIEWS (MANAGER_REVIEW rows feed
-- VW_PENDING_APPROVALS; other statuses must not)
-- -----------------------------------------------------------------------

insert into review_cycles (cycle_id, cycle_name, cycle_year, start_date, end_date, self_review_due, manager_review_due, calibration_due, status, created_by, created_date)
values (9001, '2024 Mid-Year Review', 2024, DATE '2024-06-01', DATE '2024-07-31', DATE '2024-06-21', DATE '2024-07-12', DATE '2024-07-26', 'IN_PROGRESS', 'patricia.williams@company.com', DATE '2024-05-20');

insert into performance_reviews (review_id, cycle_id, emp_id, reviewer_emp_id, review_type, status, created_by, created_date)
values (5001, 9001, 22, 21, 'MID_YEAR', 'MANAGER_REVIEW', 'SYSTEM', DATE '2024-06-10');

insert into performance_reviews (review_id, cycle_id, emp_id, reviewer_emp_id, review_type, status, created_by, created_date)
values (5002, 9001, 33, 31, 'MID_YEAR', 'MANAGER_REVIEW', 'SYSTEM', DATE '2024-06-12');

insert into performance_reviews (review_id, cycle_id, emp_id, reviewer_emp_id, review_type, status, created_by, created_date)
values (5003, 9001, 23, 21, 'MID_YEAR', 'SELF_REVIEW', 'SYSTEM', DATE '2024-06-10');

insert into performance_reviews (review_id, cycle_id, emp_id, reviewer_emp_id, review_type, status, overall_rating, rating_label, created_by, created_date)
values (5004, 9001, 42, 41, 'MID_YEAR', 'COMPLETED', 4.0, 'Exceeds Expectations', 'SYSTEM', DATE '2024-06-05');

-- Advance the sequences past the explicit primary keys inserted above.
select setval('seq_leave_balance', max(balance_id)) from leave_balances
  having max(balance_id) >= (select last_value from seq_leave_balance);
select setval('seq_leave_request', max(request_id)) from leave_requests
  having max(request_id) >= (select last_value from seq_leave_request);
select setval('seq_pay_period', max(period_id)) from pay_periods
  having max(period_id) >= (select last_value from seq_pay_period);
select setval('seq_payroll_detail', max(detail_id)) from payroll_details
  having max(detail_id) >= (select last_value from seq_payroll_detail);
select setval('seq_payroll_run', max(run_id)) from payroll_runs
  having max(run_id) >= (select last_value from seq_payroll_run);
select setval('seq_perf_review', max(review_id)) from performance_reviews
  having max(review_id) >= (select last_value from seq_perf_review);
select setval('seq_review_cycle', max(cycle_id)) from review_cycles
  having max(cycle_id) >= (select last_value from seq_review_cycle);
