-- Phase 4 – Payroll (contracts/p4-payroll). Pure-Java engine on PostgreSQL; no PL/pgSQL, no triggers.
-- (The contract names this file V6__payroll.sql; V6 was taken by the P3 employee migration.)

-- ---------------------------------------------------------------- pay_elements: ERROR sentinel
alter table pay_elements drop constraint chk_elem_type;
alter table pay_elements add constraint chk_elem_type
    check (element_type in ('EARNING', 'DEDUCTION', 'TAX', 'BENEFIT', 'REIMBURSEMENT', 'ERROR'));

insert into pay_elements (element_id, element_code, element_name, element_type, calculation_type,
                          taxable_flag, pretax_flag, employer_paid, priority_order, active_flag, created_by)
values (0, 'ERROR', 'Calculation failure sentinel', 'ERROR', 'FLAT', 'N', 'N', 'N', 0, 'N', 'P4_MIGRATION')
on conflict (element_id) do nothing;

-- ---------------------------------------------------------------- payroll_details: error contract
alter table payroll_details add column if not exists error_code varchar(40);
alter table payroll_details alter column status set not null;
alter table payroll_details add constraint chk_pd_status
    check (status in ('CALCULATED', 'ERROR', 'REVERSED'));
alter table payroll_details add constraint chk_pd_element_type
    check (element_type in ('EARNING', 'DEDUCTION', 'TAX', 'BENEFIT', 'REIMBURSEMENT', 'ERROR'));
create index if not exists ix_pd_run_emp on payroll_details (run_id, emp_id, element_id);
create index if not exists ix_pd_emp_status on payroll_details (emp_id, status);

-- Legacy seed rows that carried an ERROR status on a real element (SQLERRM rows): keep the row,
-- backfill the frozen error code so the API contract (errorCode not null on ERROR rows) holds.
update payroll_details set error_code = 'INTERNAL_ERROR'
 where status = 'ERROR' and error_code is null;

alter table payroll_runs alter column status set not null;
alter table payroll_runs alter column run_type set not null;
alter table payroll_runs add column if not exists engine varchar(10) default 'JAVA' not null;
alter table payroll_runs add column if not exists job_execution_id bigint;
alter table payroll_runs add column if not exists failure_message varchar(2000);
alter table payroll_runs add constraint chk_run_engine check (engine in ('JAVA', 'LEGACY'));
create index if not exists ix_pr_period_status on payroll_runs (period_id, status);

alter table pay_periods alter column status set not null;

-- ---------------------------------------------------------------- shadow tables (CUTOVER_PLAN §8.2)
create table payroll_details_shadow (
    shadow_id            bigint          generated by default as identity,
    run_id               bigint          not null,
    emp_id               bigint          not null,
    element_id           bigint          not null,
    element_type         varchar(20)     not null,
    amount               numeric(12,2)   not null,
    status               varchar(20)     not null,
    error_code           varchar(40),
    error_message        varchar(4000),
    engine               varchar(10)     not null,
    written_at           timestamp(0)    default current_timestamp not null,
    constraint pk_payroll_details_shadow primary key (shadow_id),
    constraint chk_pds_engine check (engine in ('JAVA', 'LEGACY')),
    constraint chk_pds_status check (status in ('CALCULATED', 'ERROR', 'REVERSED'))
);
create index ix_pds_run_engine on payroll_details_shadow (run_id, engine, emp_id, element_id);

create table payroll_shadow_reports (
    run_id               bigint          not null,
    period_id            bigint          not null,
    tax_year             smallint        not null,
    engine_flag          varchar(10)     not null,
    legacy_source        varchar(20)     not null,
    compared_at          timestamp(0)    not null,
    employees            integer         not null,
    matched              integer         not null,
    explained            integer         not null,
    unexplained          integer         not null,
    legacy_only          integer         not null,
    java_only            integer         not null,
    error_rows_legacy    integer         not null,
    error_rows_java      integer         not null,
    net_delta_cents      bigint          not null,
    lines_json           text            not null,
    constraint pk_payroll_shadow_reports primary key (run_id),
    constraint chk_psr_source check (legacy_source in ('oracle-cdc', 'recorded'))
);

-- ---------------------------------------------------------------- tax_brackets (BUG-02)
alter table tax_brackets drop constraint chk_filing_status;
alter table tax_brackets add constraint chk_filing_status
    check (filing_status in ('SINGLE', 'MARRIED_JOINT', 'MARRIED_SEPARATE', 'HEAD_OF_HOUSEHOLD', 'ALL'));
create index ix_tax_brackets_lookup on tax_brackets (tax_year, state_code, filing_status, bracket_min);

-- 2024 federal ladders: reproduce PKG_PAYROLL.calculate_federal_tax (SINGLE / MARRIED_SEPARATE /
-- MARRIED_JOINT) and add the real 2024 HEAD_OF_HOUSEHOLD ladder (declared divergence).
insert into tax_brackets (bracket_id, tax_year, filing_status, bracket_min, bracket_max, tax_rate, base_tax, state_code, active_flag, created_by) values
 (9001, 2024, 'SINGLE',           0,         11600,   0.10,      0,     null, 'Y', 'P4_MIGRATION'),
 (9002, 2024, 'SINGLE',           11600,     47150,   0.12,   1160,     null, 'Y', 'P4_MIGRATION'),
 (9003, 2024, 'SINGLE',           47150,    100525,   0.22,   5426,     null, 'Y', 'P4_MIGRATION'),
 (9004, 2024, 'SINGLE',           100525,   191950,   0.24,  17168.50,  null, 'Y', 'P4_MIGRATION'),
 (9005, 2024, 'SINGLE',           191950,   243725,   0.32,  39110.50,  null, 'Y', 'P4_MIGRATION'),
 (9006, 2024, 'SINGLE',           243725,   609350,   0.35,  55678.50,  null, 'Y', 'P4_MIGRATION'),
 (9007, 2024, 'SINGLE',           609350,   null,     0.37, 183647.25,  null, 'Y', 'P4_MIGRATION'),
 (9008, 2024, 'MARRIED_SEPARATE', 0,         11600,   0.10,      0,     null, 'Y', 'P4_MIGRATION'),
 (9009, 2024, 'MARRIED_SEPARATE', 11600,     47150,   0.12,   1160,     null, 'Y', 'P4_MIGRATION'),
 (9010, 2024, 'MARRIED_SEPARATE', 47150,    100525,   0.22,   5426,     null, 'Y', 'P4_MIGRATION'),
 (9011, 2024, 'MARRIED_SEPARATE', 100525,   191950,   0.24,  17168.50,  null, 'Y', 'P4_MIGRATION'),
 (9012, 2024, 'MARRIED_SEPARATE', 191950,   243725,   0.32,  39110.50,  null, 'Y', 'P4_MIGRATION'),
 (9013, 2024, 'MARRIED_SEPARATE', 243725,   609350,   0.35,  55678.50,  null, 'Y', 'P4_MIGRATION'),
 (9014, 2024, 'MARRIED_SEPARATE', 609350,   null,     0.37, 183647.25,  null, 'Y', 'P4_MIGRATION'),
 (9015, 2024, 'MARRIED_JOINT',    0,         23200,   0.10,      0,     null, 'Y', 'P4_MIGRATION'),
 (9016, 2024, 'MARRIED_JOINT',    23200,     94300,   0.12,   2320,     null, 'Y', 'P4_MIGRATION'),
 (9017, 2024, 'MARRIED_JOINT',    94300,    201050,   0.22,  10852,     null, 'Y', 'P4_MIGRATION'),
 (9018, 2024, 'MARRIED_JOINT',    201050,   383900,   0.24,  34337,     null, 'Y', 'P4_MIGRATION'),
 (9019, 2024, 'MARRIED_JOINT',    383900,   487450,   0.32,  78221,     null, 'Y', 'P4_MIGRATION'),
 (9020, 2024, 'MARRIED_JOINT',    487450,   731200,   0.35, 111357,     null, 'Y', 'P4_MIGRATION'),
 (9021, 2024, 'MARRIED_JOINT',    731200,   null,     0.37, 196669.50,  null, 'Y', 'P4_MIGRATION'),
 (9022, 2024, 'HEAD_OF_HOUSEHOLD', 0,        16550,   0.10,      0,     null, 'Y', 'P4_MIGRATION'),
 (9023, 2024, 'HEAD_OF_HOUSEHOLD', 16550,    63100,   0.12,   1655,     null, 'Y', 'P4_MIGRATION'),
 (9024, 2024, 'HEAD_OF_HOUSEHOLD', 63100,   100500,   0.22,   7241,     null, 'Y', 'P4_MIGRATION'),
 (9025, 2024, 'HEAD_OF_HOUSEHOLD', 100500,  191950,   0.24,  15469,     null, 'Y', 'P4_MIGRATION'),
 (9026, 2024, 'HEAD_OF_HOUSEHOLD', 191950,  243700,   0.32,  37417,     null, 'Y', 'P4_MIGRATION'),
 (9027, 2024, 'HEAD_OF_HOUSEHOLD', 243700,  609350,   0.35,  53977,     null, 'Y', 'P4_MIGRATION'),
 (9028, 2024, 'HEAD_OF_HOUSEHOLD', 609350,  null,     0.37, 181954.50,  null, 'Y', 'P4_MIGRATION');

-- 2024 state flat rates = PKG_PAYROLL.calculate_state_tax CASE list. The legacy `ELSE 0.05`
-- fallback is deliberately NOT a row: an unlisted state is MISSING_TAX_RATE (declared divergence
-- UNLISTED_STATE_FALLBACK).
insert into tax_brackets (bracket_id, tax_year, filing_status, bracket_min, bracket_max, tax_rate, base_tax, state_code, active_flag, created_by) values
 (9029, 2024, 'ALL', 0, null, 0.0725, 0, 'CA', 'Y', 'P4_MIGRATION'),
 (9030, 2024, 'ALL', 0, null, 0.0685, 0, 'NY', 'Y', 'P4_MIGRATION'),
 (9031, 2024, 'ALL', 0, null, 0.0000, 0, 'TX', 'Y', 'P4_MIGRATION'),
 (9032, 2024, 'ALL', 0, null, 0.0000, 0, 'FL', 'Y', 'P4_MIGRATION'),
 (9033, 2024, 'ALL', 0, null, 0.0000, 0, 'WA', 'Y', 'P4_MIGRATION'),
 (9034, 2024, 'ALL', 0, null, 0.0495, 0, 'IL', 'Y', 'P4_MIGRATION'),
 (9035, 2024, 'ALL', 0, null, 0.0307, 0, 'PA', 'Y', 'P4_MIGRATION'),
 (9036, 2024, 'ALL', 0, null, 0.0400, 0, 'OH', 'Y', 'P4_MIGRATION'),
 (9037, 2024, 'ALL', 0, null, 0.0637, 0, 'NJ', 'Y', 'P4_MIGRATION'),
 (9038, 2024, 'ALL', 0, null, 0.0500, 0, 'MA', 'Y', 'P4_MIGRATION');

-- 2024 scalars (PKG_PAYROLL constants). Contract logical names PARAM_CATEGORY='TAX' /
-- PARAM_NAME='<year>.<NAME>' map onto the baseline's physical columns param_group / param_code.
insert into system_parameters (param_id, param_group, param_code, param_value, param_description, data_type, editable_flag, created_by) values
 (9001, 'TAX', '2024.STD_DEDUCTION.SINGLE',            '14600.00',  '2024 standard deduction (single)',              'NUMBER', 'Y', 'P4_MIGRATION'),
 (9002, 'TAX', '2024.STD_DEDUCTION.MARRIED_SEPARATE',  '14600.00',  '2024 standard deduction (married separate)',    'NUMBER', 'Y', 'P4_MIGRATION'),
 (9003, 'TAX', '2024.STD_DEDUCTION.HEAD_OF_HOUSEHOLD', '14600.00',  '2024 standard deduction (head of household; legacy used the single figure)', 'NUMBER', 'Y', 'P4_MIGRATION'),
 (9004, 'TAX', '2024.STD_DEDUCTION.MARRIED_JOINT',     '29200.00',  '2024 standard deduction (married joint)',       'NUMBER', 'Y', 'P4_MIGRATION'),
 (9005, 'TAX', '2024.ALLOWANCE',                '4300.00',   '2024 per-allowance amount',                     'NUMBER', 'Y', 'P4_MIGRATION'),
 (9006, 'TAX', '2024.SS_WAGE_BASE',                    '168600.00', '2024 Social Security wage base',                'NUMBER', 'Y', 'P4_MIGRATION'),
 (9007, 'TAX', '2024.SS_RATE',                         '0.0620',    '2024 Social Security rate',                     'NUMBER', 'Y', 'P4_MIGRATION'),
 (9008, 'TAX', '2024.MEDICARE_RATE',                   '0.0145',    '2024 Medicare rate',                            'NUMBER', 'Y', 'P4_MIGRATION'),
 (9009, 'TAX', '2024.MEDICARE_ADDL_RATE',              '0.0090',    '2024 additional Medicare rate',                 'NUMBER', 'Y', 'P4_MIGRATION'),
 (9010, 'TAX', '2024.MEDICARE_ADDL_THRESHOLD',         '200000.00', '2024 additional Medicare threshold',            'NUMBER', 'Y', 'P4_MIGRATION');

-- ---------------------------------------------------------------- audit actions used by P4
alter table audit_log drop constraint chk_audit_action;
alter table audit_log add constraint chk_audit_action
    check (action_type in ('INSERT', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'LOGIN', 'LOGOUT',
                           'PERIOD_CLOSE', 'PAYROLL_APPROVE', 'PAYROLL_REVERSE', 'REGISTER_DOWNLOAD'));

-- ---------------------------------------------------------------- Spring Batch metadata (payrollCalculation job)
-- Verbatim org/springframework/batch/core/schema-postgresql.sql (Spring Batch 5.1); owned by Flyway so
-- spring.batch.jdbc.initialize-schema stays 'never'.
CREATE TABLE BATCH_JOB_INSTANCE  (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT ,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;
CREATE TABLE BATCH_JOB_EXECUTION  (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT  ,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
	JOB_EXECUTION_ID BIGINT NOT NULL ,
	PARAMETER_NAME VARCHAR(100) NOT NULL ,
	PARAMETER_TYPE VARCHAR(100) NOT NULL ,
	PARAMETER_VALUE VARCHAR(2500) ,
	IDENTIFYING CHAR(1) NOT NULL ,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;
CREATE TABLE BATCH_STEP_EXECUTION  (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL ,
	END_TIME TIMESTAMP DEFAULT NULL ,
	STATUS VARCHAR(10) ,
	COMMIT_COUNT BIGINT ,
	READ_COUNT BIGINT ,
	FILTER_COUNT BIGINT ,
	WRITE_COUNT BIGINT ,
	READ_SKIP_COUNT BIGINT ,
	WRITE_SKIP_COUNT BIGINT ,
	PROCESS_SKIP_COUNT BIGINT ,
	ROLLBACK_COUNT BIGINT ,
	EXIT_CODE VARCHAR(2500) ,
	EXIT_MESSAGE VARCHAR(2500) ,
	LAST_UPDATED TIMESTAMP,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT ,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;
CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
